### PR TITLE
FIX config FRR genaration of community-list

### PR DESCRIPTION
**Pull request by otavioti**
In version of frr used by DANOS de command of community-list is "bgp community-list" unless  "ip communty-list"

Signed-off-by: Otavio Augusto <otavioti@gmail.com>

### CODE REVIEW

**Review by deastoe — CHANGES_REQUESTED** [review]
Thanks for your contribution @otavioti!

Please could you amend your commit message to include the signed-off-by line - that will fix the failing DCO check.

Please review https://danosproject.atlassian.net/wiki/spaces/DAN/pages/3276830/Contributing+to+the+DANOS+source+code for information on the DCO and meaning of the Signed-off-by line.

**Comment by deastoe** [comment]
@otavioti it looks like the latest push has removed the changes to policy.json.

You can get them back as a single signed off commit on top of master by doing something like:
```
git checkout patch-2
git reset --hard 033556a6a3469db5e64187cc947ac7a689ab9cde
git cherry-pick -s a287084f113bf7d2d9c5bd7848623b47fef4bdee
```

**Comment by deastoe** [comment]
@otavioti we're currently preparing the next release of DANOS (2009) and we'd like to include this fix.

If you are able to address the outstanding comment (addition of Signed-off-by line) by 14th September we can include your contribution.
If not, or you no longer wish to proceed with the PR, we can push a fix for the reported issue in time for the release.

Thanks again for your interest and contribution to DANOS!

**Comment by deastoe** [comment]
Fixed in cdde377b7968a73b667d7e887a0a428fe650d963.

**Comment by nickbroon** [comment]
Fixed in cdde377

**Pull request closed without merging**
